import { LessonContent } from '../../types/LessonTypes';

export const lesson_8_5: LessonContent = {
  title: 'Type Erasure and Limitations',
  type: 'lesson',
  duration: '25 min',
  module: 'Generics and Type Safety',
  content: {
    overview: 'Understand type erasure in Java generics and its limitations. This lesson covers how generics are implemented through type erasure, the restrictions it imposes, and strategies to work around these limitations.',
    objectives: [
      'Understand how type erasure works in Java generics',
      'Learn about the limitations imposed by type erasure',
      'Master techniques to work around type erasure restrictions',
      'Apply best practices for handling generic type information',
      'Implement solutions for common generic limitations',
      'Avoid pitfalls related to type erasure'
    ],
    theory: `
      <div class="bg-gradient-to-r from-red-600 to-orange-600 text-white p-6 rounded-lg mb-8 shadow-2xl">
        <h1 class="text-3xl font-bold m-0 flex items-center">
          <span class="w-3 h-10 bg-white rounded mr-4"></span>
          Type Erasure and Limitations
        </h1>
        <p class="mt-3 text-red-100 text-lg">Understanding Java generics implementation and restrictions</p>
      </div>

      <div class="space-y-8">
        <section class="bg-white p-6 rounded-lg shadow-lg border-l-4 border-red-500">
          <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
            <span class="bg-red-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3 text-sm font-bold">1</span>
            What is Type Erasure?
          </h2>
          <p class="text-gray-700 mb-4 leading-relaxed text-lg">
            Type erasure is the process by which the Java compiler removes all generic type information at compile time. 
            This means that at runtime, generic types are replaced with their bounds or Object if no bounds are specified. 
            This approach was chosen to maintain backward compatibility with pre-generics Java code.
          </p>
          <div class="bg-red-50 p-4 rounded-lg border-l-4 border-red-400 mb-4">
            <h4 class="font-bold text-red-800 mb-2">💡 Key Concept</h4>
            <p class="text-red-700">Type erasure enables backward compatibility but imposes significant limitations on what you can do with generic types at runtime.</p>
          </div>
        </section>

        <section class="bg-white p-6 rounded-lg shadow-lg border-l-4 border-blue-500">
          <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
            <span class="bg-blue-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3 text-sm font-bold">2</span>
            How Type Erasure Works
          </h2>
          <div class="space-y-4">
            <p class="text-gray-700">Understanding the type erasure process:</p>
            
            <div class="grid md:grid-cols-2 gap-6">
              <div class="bg-blue-50 p-4 rounded-lg">
                <h4 class="font-bold text-blue-800 mb-2">Type Erasure Process</h4>
                <ul class="space-y-2 text-gray-700">
                  <li>• Generic type information removed at compile time</li>
                  <li>• Type parameters replaced with bounds or Object</li>
                  <li>• Bridge methods generated for type safety</li>
                  <li>• Runtime representation is raw type</li>
                </ul>
                <div class="bg-gray-900 text-green-400 p-2 rounded font-mono text-sm mt-2">
                  // Before type erasure<br/>
                  public class Box<T> {<br/>
                  &nbsp;&nbsp;private T item;<br/>
                  &nbsp;&nbsp;public void set(T item) { this.item = item; }<br/>
                  &nbsp;&nbsp;public T get() { return item; }<br/>
                  }<br/>
                  <br/>
                  // After type erasure<br/>
                  public class Box {<br/>
                  &nbsp;&nbsp;private Object item;<br/>
                  &nbsp;&nbsp;public void set(Object item) { this.item = item; }<br/>
                  &nbsp;&nbsp;public Object get() { return item; }<br/>
                  }
                </div>
              </div>
              <div class="bg-green-50 p-4 rounded-lg">
                <h4 class="font-bold text-green-800 mb-2">Bridge Methods</h4>
                <ul class="space-y-2 text-gray-700">
                  <li>• Generated by compiler for type safety</li>
                  <li>• Handle inheritance with generics</li>
                  <li>• Ensure correct method signatures</li>
                  <li>• Maintain polymorphic behavior</li>
                </ul>
                <div class="bg-gray-900 text-green-400 p-2 rounded font-mono text-sm mt-2">
                  // Bridge method example<br/>
                  public class MyComparator implements Comparator<String> {<br/>
                  &nbsp;&nbsp;// Compiler generates bridge method:<br/>
                  &nbsp;&nbsp;// public int compare(Object o1, Object o2)<br/>
                  &nbsp;&nbsp;public int compare(String s1, String s2) {<br/>
                  &nbsp;&nbsp;&nbsp;&nbsp;return s1.compareTo(s2);<br/>
                  &nbsp;&nbsp;}<br/>
                  }
                </div>
              </div>
            </div>
          </div>
        </section>

        <section class="bg-white p-6 rounded-lg shadow-lg border-l-4 border-purple-500">
          <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
            <span class="bg-purple-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3 text-sm font-bold">3</span>
            Limitations of Type Erasure
          </h2>
          <div class="space-y-4">
            <p class="text-gray-700">Common limitations imposed by type erasure:</p>
            
            <div class="bg-gray-900 text-green-400 p-4 rounded font-mono text-sm">
              // These operations are NOT allowed due to type erasure:<br/>
              <br/>
              // 1. Creating instances of generic types<br/>
              // public <T> void createInstance() {<br/>
              // &nbsp;&nbsp;T instance = new T(); // Compilation error<br/>
              // }<br/>
              <br/>
              // 2. Creating arrays of generic types<br/>
              // List<String>[] array = new List<String>[10]; // Compilation error<br/>
              <br/>
              // 3. Using instanceof with generic types<br/>
              // if (list instanceof List<String>) // Compilation error<br/>
              <br/>
              // 4. Catching generic exceptions<br/>
              // catch (GenericException<T> e) // Compilation error
            </div>
            
            <div class="overflow-x-auto">
              <table class="w-full text-sm border border-gray-200">
                <thead class="bg-purple-50">
                  <tr>
                    <th class="text-left p-3 font-bold border-b">Limitation</th>
                    <th class="text-left p-3 font-bold border-b">Reason</th>
                    <th class="text-left p-3 font-bold border-b">Workaround</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="border-b">
                    <td class="p-3">Cannot create generic instances</td>
                    <td class="p-3">Type information erased at runtime</td>
                    <td class="p-3">Pass Class objects as parameters</td>
                  </tr>
                  <tr class="border-b bg-gray-50">
                    <td class="p-3">Cannot create generic arrays</td>
                    <td class="p-3">Array creation requires runtime type info</td>
                    <td class="p-3">Use unchecked casts or collections</td>
                  </tr>
                  <tr class="border-b">
                    <td class="p-3">Cannot use instanceof with generics</td>
                    <td class="p-3">Generic type info not available at runtime</td>
                    <td class="p-3">Check raw type or use Class objects</td>
                  </tr>
                  <tr class="border-b bg-gray-50">
                    <td class="p-3">Cannot throw/catch generic exceptions</td>
                    <td class="p-3">Exception handling requires concrete types</td>
                    <td class="p-3">Use non-generic exception classes</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </section>

        <section class="bg-white p-6 rounded-lg shadow-lg border-l-4 border-orange-500">
          <h2 class="text-2xl font-bold text-gray-800 mb-4 flex items-center">
            <span class="bg-orange-500 text-white rounded-full w-8 h-8 flex items-center justify-center mr-3 text-sm font-bold">4</span>
            Working Around Type Erasure
          </h2>
          <div class="space-y-4">
            <p class="text-gray-700">Techniques to overcome type erasure limitations:</p>
            
            <div class="grid md:grid-cols-2 gap-6">
              <div class="bg-orange-50 p-4 rounded-lg">
                <h4 class="font-bold text-orange-800 mb-2">Class Object Pattern</h4>
                <ul class="space-y-2 text-gray-700">
                  <li>• Pass Class objects to generic methods</li>
                  <li>• Use reflection for instance creation</li>
                  <li>• Maintain type safety at runtime</li>
                </ul>
                <div class="bg-gray-900 text-green-400 p-2 rounded font-mono text-sm mt-2">
                  public <T> T createInstance(Class<T> clazz) <br/>
                  &nbsp;&nbsp;&nbsp;&nbsp;throws InstantiationException, IllegalAccessException {<br/>
                  &nbsp;&nbsp;return clazz.newInstance();<br/>
                  }<br/>
                  <br/>
                  // Usage<br/>
                  String str = createInstance(String.class);
                </div>
              </div>
              <div class="bg-red-50 p-4 rounded-lg">
                <h4 class="font-bold text-red-800 mb-2">Type Tokens</h4>
                <ul class="space-y-2 text-gray-700">
                  <li>• Capture generic type information</li>
                  <li>• Use anonymous inner classes</li>
                  <li>• Enable runtime type checking</li>
                </ul>
                <div class="bg-gray-900 text-green-400 p-2 rounded font-mono text-sm mt-2">
                  // Type token pattern<br/>
                  public abstract class TypeReference<T> {<br/>
                  &nbsp;&nbsp;private final Type type;<br/>
                  &nbsp;&nbsp;protected TypeReference() {<br/>
                  &nbsp;&nbsp;&nbsp;&nbsp;Type superClass = getClass().getGenericSuperclass();<br/>
                  &nbsp;&nbsp;&nbsp;&nbsp;type = ((ParameterizedType) superClass)<br/>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.getActualTypeArguments()[0];<br/>
                  &nbsp;&nbsp;}<br/>
                  &nbsp;&nbsp;public Type getType() { return type; }<br/>
                  }<br/>
                  <br/>
                  // Usage<br/>
                  TypeReference<List<String>> ref = new TypeReference<List<String>>() {};
                </div>
              </div>
            </div>
          </div>
        </section>

        <section class="bg-gradient-to-r from-gray-100 to-gray-200 p-6 rounded-lg">
          <h2 class="text-2xl font-bold text-gray-800 mb-4">🎯 Best Practices for Type Erasure</h2>
          <div class="grid md:grid-cols-2 gap-6">
            <div class="bg-white p-4 rounded-lg shadow">
              <h4 class="font-bold text-gray-800 mb-3">✅ Do's</h4>
              <ul class="space-y-2 text-gray-700">
                <li>• Use Class objects for instance creation</li>
                <li>• Apply type tokens for runtime type information</li>
                <li>• Leverage reflection for generic operations</li>
                <li>• Check raw types when generic info unavailable</li>
                <li>• Use @SuppressWarnings judiciously</li>
              </ul>
            </div>
            <div class="bg-white p-4 rounded-lg shadow">
              <h4 class="font-bold text-gray-800 mb-3">🚫 Don'ts</h4>
              <ul class="space-y-2 text-gray-700">
                <li>• Don't ignore type erasure limitations</li>
                <li>• Don't use unchecked casts without validation</li>
                <li>• Don't create arrays of parameterized types</li>
                <li>• Don't use generic type info at runtime</li>
                <li>• Don't suppress warnings unnecessarily</li>
              </ul>
            </div>
          </div>
        </section>
      </div>
    `,
    codeExample: `/**
 * TypeErasureAndLimitationsDemo.java
 * 
 * This comprehensive example demonstrates type erasure and its limitations in Java generics:
 * - How type erasure works and its effects
 * - Common limitations imposed by type erasure
 * - Techniques to work around type erasure restrictions
 * - Best practices for handling generic type information
 * 
 * Run this program to see type erasure in action.
 */

import java.lang.reflect.*;
import java.util.*;

// Generic class to demonstrate type erasure
class Box<T> {
    private T item;
    
    public void set(T item) {
        this.item = item;
    }
    
    public T get() {
        return item;
    }
    
    // Method that would be affected by type erasure
    public void inspectType() {
        // This won't work due to type erasure:
        // System.out.println("Type is: " + T.class); // Compilation error
        
        // We can only work with Object at runtime
        System.out.println("Item class: " + (item != null ? item.getClass() : "null"));
    }
}

// Generic class with bounded type parameter
class NumberBox<T extends Number> {
    private T number;
    
    public NumberBox(T number) {
        this.number = number;
    }
    
    public double getDoubleValue() {
        // This works because of the bound
        return number.doubleValue();
    }
    
    public T getNumber() {
        return number;
    }
}

// Class to demonstrate bridge methods
class MyComparator implements Comparator<String> {
    @Override
    public int compare(String s1, String s2) {
        return s1.compareTo(s2);
    }
    
    // Compiler generates a bridge method:
    // public int compare(Object o1, Object o2) {
    //     return compare((String) o1, (String) o2);
    // }
}

// Type token pattern for capturing generic type information
abstract class TypeReference<T> {
    private final Type type;
    
    protected TypeReference() {
        Type superClass = getClass().getGenericSuperclass();
        if (superClass instanceof ParameterizedType) {
            type = ((ParameterizedType) superClass).getActualTypeArguments()[0];
        } else {
            throw new IllegalArgumentException("TypeReference must be subclassed with generic type");
        }
    }
    
    public Type getType() {
        return type;
    }
}

public class TypeErasureAndLimitationsDemo {
    
    public static void main(String[] args) {
        printHeader();
        
        // Demonstrate type erasure effects
        demonstrateTypeErasure();
        
        // Demonstrate limitations and workarounds
        demonstrateLimitations();
        
        // Demonstrate bridge methods
        demonstrateBridgeMethods();
        
        // Demonstrate type tokens
        demonstrateTypeTokens();
        
        printFooter();
    }
    
    private static void printHeader() {
        System.out.println("╔══════════════════════════════════════════════════════════════╗");
        System.out.println("║         TYPE ERASURE AND LIMITATIONS DEMO                    ║");
        System.out.println("║         Understanding Java generics implementation           ║");
        System.out.println("╚══════════════════════════════════════════════════════════════╝");
        System.out.println();
    }
    
    private static void demonstrateTypeErasure() {
        System.out.println("🔸 TYPE ERASURE DEMONSTRATION");
        System.out.println("   ───────────────────────────");
        
        // Create generic boxes with different types
        Box<String> stringBox = new Box<>();
        Box<Integer> intBox = new Box<>();
        
        stringBox.set("Hello");
        intBox.set(42);
        
        System.out.println("   String box contains: " + stringBox.get());
        System.out.println("   Integer box contains: " + intBox.get());
        
        // Demonstrate type inspection
        stringBox.inspectType();
        intBox.inspectType();
        
        // At runtime, both boxes are the same class
        System.out.println("   String box class: " + stringBox.getClass());
        System.out.println("   Integer box class: " + intBox.getClass());
        System.out.println("   Classes are equal: " + (stringBox.getClass() == intBox.getClass()));
        
        System.out.println();
    }
    
    private static void demonstrateLimitations() {
        System.out.println("🔸 TYPE ERASURE LIMITATIONS DEMONSTRATION");
        System.out.println("   ────────────────────────────────────────");
        
        // Demonstrate what you CAN'T do due to type erasure
        
        // 1. Cannot create instances of generic types directly
        System.out.println("   1. Cannot create instances of generic types:");
        // createGenericInstance(); // This would cause compilation error
        
        // 2. Cannot create arrays of generic types
        System.out.println("   2. Cannot create arrays of generic types:");
        // Box<String>[] array = new Box<String>[10]; // Compilation error
        
        // 3. Cannot use instanceof with generic types
        System.out.println("   3. Cannot use instanceof with generic types:");
        Box<String> box = new Box<>();
        // if (box instanceof Box<String>) // Compilation error
        if (box instanceof Box) // This works but checks raw type
            System.out.println("      Box is instance of raw Box type");
        
        // Workarounds for these limitations
        System.out.println("   Workarounds:");
        
        // Using Class object for instance creation
        try {
            String str = createInstance(String.class);
            System.out.println("      Created String instance: " + str);
            
            Integer integer = createInstance(Integer.class);
            System.out.println("      Created Integer instance: " + integer);
        } catch (Exception e) {
            System.out.println("      Error creating instances: " + e.getMessage());
        }
        
        // Using collections instead of arrays
        List<Box<String>> boxList = new ArrayList<>();
        boxList.add(new Box<>());
        System.out.println("      Created List of Box<String>: " + boxList.size() + " elements");
        
        System.out.println();
    }
    
    // Workaround for creating generic instances
    public static <T> T createInstance(Class<T> clazz) 
            throws InstantiationException, IllegalAccessException {
        return clazz.newInstance();
    }
    
    // Another workaround using Supplier
    public static <T> T createInstance(Supplier<T> supplier) {
        return supplier.get();
    }
    
    private static void demonstrateBridgeMethods() {
        System.out.println("🔸 BRIDGE METHODS DEMONSTRATION");
        System.out.println("   ─────────────────────────────");
        
        // Create comparator instance
        MyComparator comparator = new MyComparator();
        
        // Demonstrate bridge method existence
        System.out.println("   MyComparator methods:");
        Method[] methods = comparator.getClass().getDeclaredMethods();
        for (Method method : methods) {
            if (method.getName().equals("compare")) {
                System.out.println("      " + method);
            }
        }
        
        // Use the comparator
        String result1 = comparator.compare("Apple", "Banana") < 0 ? "Apple < Banana" : "Apple >= Banana";
        String result2 = comparator.compare("Cherry", "Banana") > 0 ? "Cherry > Banana" : "Cherry <= Banana";
        
        System.out.println("      Comparing Apple and Banana: " + result1);
        System.out.println("      Comparing Cherry and Banana: " + result2);
        
        System.out.println();
    }
    
    private static void demonstrateTypeTokens() {
        System.out.println("🔸 TYPE TOKENS DEMONSTRATION");
        System.out.println("   ──────────────────────────");
        
        // Create type tokens for different generic types
        TypeReference<List<String>> stringListType = new TypeReference<List<String>>() {};
        TypeReference<Map<String, Integer>> mapType = new TypeReference<Map<String, Integer>>() {};
        TypeReference<Set<Double>> setType = new TypeReference<Set<Double>>() {};
        
        // Get type information
        System.out.println("   String list type: " + stringListType.getType());
        System.out.println("   Map type: " + mapType.getType());
        System.out.println("   Set type: " + setType.getType());
        
        // Extract actual type arguments
        if (stringListType.getType() instanceof ParameterizedType) {
            ParameterizedType pt = (ParameterizedType) stringListType.getType();
            System.out.println("   String list actual type arguments: " + 
                             Arrays.toString(pt.getActualTypeArguments()));
        }
        
        // Use type tokens for serialization/deserialization
        System.out.println("   Type tokens enable proper deserialization of generic types");
        System.out.println("   Libraries like Gson and Jackson use similar techniques");
        
        System.out.println();
    }
    
    private static void printFooter() {
        System.out.println("╔══════════════════════════════════════════════════════════════╗");
        System.out.println("║                    🎉 DEMONSTRATION COMPLETE! 🎉           ║");
        System.out.println("║                                                              ║");
        System.out.println("║  You've learned about:                                       ║");
        System.out.println("║  • How type erasure works and its effects                    ║");
        System.out.println("║  • Common limitations imposed by type erasure                ║");
        System.out.println("║  • Techniques to work around type erasure restrictions       ║");
        System.out.println("║  • Best practices for handling generic type information      ║");
        System.out.println("║                                                              ║");
        System.out.println("║  Remember to:                                                ║");
        System.out.println("║  • Use Class objects for instance creation                   ║");
        System.out.println("║  • Apply type tokens for runtime type information            ║");
        System.out.println("║  • Leverage reflection for generic operations                ║");
        System.out.println("╚══════════════════════════════════════════════════════════════╝");
    }
}

`,
    exercise: `
1. Create a generic method that uses Class<T> to create instances of any type.
2. Explain why you cannot create arrays of generic types like List<String>[].
3. Create a method that checks if an object is an instance of a raw type instead of a generic type.
4. Write a method that uses reflection to work around type erasure limitations.
5. Create a type token pattern to capture generic type information at runtime.
`
  }
};